version: "3.8"

services:
  balancer:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    build:
      context: .
      dockerfile: Dockerfile
    command: ["lb"]
    ports:
      - "8090:8090"
    environment:
      - INTEGRATION_TEST=true
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - testnet

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server"]
    environment:
      - SERVER_NAME=server1
    networks:
      - testnet

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server"]
    environment:
      - SERVER_NAME=server2
    networks:
      - testnet

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server"]
    environment:
      - SERVER_NAME=server3
    networks:
      - testnet

  integration-test:
    image: golang:1.24
    volumes:
      - .:/go/src/practice-4
    working_dir: /go/src/practice-4
    command: ["go", "test", "./integration"]
    depends_on:
      - balancer
    environment:
      - INTEGRATION_TEST=1
    networks:
      - testnet


networks:
  testnet:
    driver: bridge
