name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
        env:
          DOCKER_BUILDKIT: 1